import { type Session } from "next-auth";
import { type ReactNode } from "react";
import Head from "next/head";
import { SessionProvider } from "next-auth/react";
import { type AppType } from "next/app";
import { WagmiConfig } from "wagmi";
import { RainbowKitProvider } from "@rainbow-me/rainbowkit";
import { chains, configForWagmi } from "~/configs/wagmi";
import { api } from "~/utils/api";
import { customRainbowTheme } from "~/configs/rainbowkit";
import "node_modules/@rainbow-me/rainbowkit/dist/index.css";
import "~/styles/globals.css";

//TEMP
import Base from "~/layouts/Base";

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  //@ts-ignore
  const getLayout = Component.getLayout ?? ((page: any) => <Base>{page}</Base>);

  return (
    <>
      <Head>
        <title>loyalty</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/Lunchtype22-Regular.ttf"
          as="font"
          type="font/ttf"
          crossOrigin="anonymous"
        />
      </Head>

      <SessionProvider session={session}>
        <WagmiConfig config={configForWagmi}>
          <RainbowKitProvider
            chains={chains}
            theme={customRainbowTheme}
            modalSize="wide"
          >
            {getLayout(<Component {...pageProps} />)}
          </RainbowKitProvider>
        </WagmiConfig>
      </SessionProvider>
    </>
  );
};

export default api.withTRPC(MyApp);
